# Generated by Django 4.2 on 2023-05-22 15:58

import charities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charities", "0002_rename_assigned_benifactor_task_assigned_benefactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefactor",
            name="experience",
            field=models.SmallIntegerField(
                choices=[(0, "Beginner"), (1, "Intermediate"), (2, "Expert")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="reg_number",
            field=models.CharField(
                max_length=10, validators=[charities.validators.RegNumberValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="gender_limit",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("MF", "Unset")],
                default="MF",
                max_length=2,
            ),
        ),
    ]
